kind: ReplicationController
apiVersion: v1
metadata:
  annotations:
    openshift.io/deployment-config.name: django2
    openshift.io/deployer-pod.completed-at: '2019-07-22 11:51:51 +0000 UTC'
    openshift.io/deployment.phase: Complete
    openshift.io/deployer-pod.created-at: '2019-07-22 11:51:30 +0000 UTC'
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment.status-reason: config change
    openshift.io/deployment.replicas: '1'
    openshift.io/encoded-deployment-config: >
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"django2","namespace":"oc","selfLink":"/apis/apps.openshift.io/v1/namespaces/oc/deploymentconfigs/django2","uid":"ad108a84-ac76-11e9-bbb0-0a580a820059","resourceVersion":"45054762","generation":2,"creationTimestamp":"2019-07-22T11:48:52Z","labels":{"app":"django2"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["django2"],"from":{"kind":"ImageStreamTag","namespace":"oc","name":"django2:latest"},"lastTriggeredImage":"image-registry.openshift-image-registry.svc:5000/oc/django2@sha256:74da84c851c2458777fe0bf89fd7c890b67e028c708f22971c80cf02276dc9b4"}},{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"django2","deploymentconfig":"django2"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"django2","deploymentconfig":"django2"}},"spec":{"containers":[{"name":"django2","image":"image-registry.openshift-image-registry.svc:5000/oc/django2@sha256:74da84c851c2458777fe0bf89fd7c890b67e028c708f22971c80cf02276dc9b4","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config
      change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2019-07-22T11:48:52Z","lastTransitionTime":"2019-07-22T11:48:52Z","message":"Deployment
      config does not have minimum availability."}]}}
    openshift.io/deployer-pod.name: django2-1-deploy
  selfLink: /api/v1/namespaces/oc/replicationcontrollers/django2-1
  resourceVersion: '45055184'
  name: django2-1
  uid: 0b6b9f76-ac77-11e9-9d75-06a98f27bd4e
  creationTimestamp: '2019-07-22T11:51:30Z'
  generation: 2
  namespace: oc
  ownerReferences:
    - apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: django2
      uid: ad108a84-ac76-11e9-bbb0-0a580a820059
      controller: true
      blockOwnerDeletion: true
  labels:
    app: django2
    openshift.io/deployment-config.name: django2
spec:
  replicas: 1
  selector:
    app: django2
    deployment: django2-1
    deploymentconfig: django2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: django2
        deployment: django2-1
        deploymentconfig: django2
      annotations:
        openshift.io/deployment-config.latest-version: '1'
        openshift.io/deployment-config.name: django2
        openshift.io/deployment.name: django2-1
    spec:
      containers:
        - name: django2
          image: >-
            image-registry.openshift-image-registry.svc:5000/oc/django2@sha256:74da84c851c2458777fe0bf89fd7c890b67e028c708f22971c80cf02276dc9b4
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  observedGeneration: 2

